version: "3.8"

services:
  chrome:
    container_name: "chrome"
    hostname: chrome
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://chrome:4444"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - type: volume
        source: data-volume
        target: /tmp

  python_script:
    build: .
    depends_on:
      chrome:
        condition: service_healthy
    volumes:
      - type: volume
        source: data-volume
        target: /tmp

volumes:
  data-volume:
