name: CI/CD Pipeline
on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Add your test steps here
      - name: Run Unit Tests
        run: |
          pytest .

      - name: Run Data Tests
        run: |
          cd tests && great_expectations checkpoint run ship_emissions_checks

      - name: Run Code Style Checks
        run: |
          pip install black isort flake8
          black --check .
          isort --check-only .
          flake8

      # Add your Docker build steps here
      - name: Build Docker Image
        run: |
          docker build -t ship_emissions .
